In [1]:
#Importing all the required libraries 
import selenium 
from bs4 import BeautifulSoup
from selenium import webdriver
import time 
import pandas as pd 
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotInteractableException
import requests 
import re
import warnings 
warnings.simplefilter("ignore")

**Q1) Scrape the details of most viewed videos on YouTube from Wikipedia.<br>
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos<br>
You need to find following details:<br>
A) Rank<br>
B) Name<br>
C) Artist<br>
D) Upload date<br>
E) Views**<br>

In [46]:
#Connecting to the webdriver and opening the wikipedia
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [47]:
#scraping the rank of the video  
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    rank.append("-")
    
#scraping the name of the video 
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('-')
        
#scraping the artist of the video 
artist=[]
try:
    artists=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist.append('-')
    
#scraping the upload date of the video     
upload_date=[]
try:
    upload_date_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in upload_date_list:
        upload_date.append(i.text)
except NoSuchElementException:#handling no such element exception
    upload_date.append('-')
    
#scraping the views of the video     
views=[]
try:
    views_list=driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in views_list:
        views.append(i.text)
except NoSuchElementException:#handling no such element exception
    views.append('-')  

#creating the DataFrame
df=pd.DataFrame({})
df["Rank"]=rank
df['Name']=name
df['Artist']=artist
df["Upload_date"]=upload_date
df["Views(in billions)"]=views
df

,Rank,Name,Artist,Upload_date,Views(in billions)
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.18
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.74
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.16
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.61
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.41
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.97
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,"February 27, 2018",4.56
7,8.,"""Masha and the Bear – Recipe for Disaster""[22]",Get Movies,"January 31, 2012",4.48
8,9.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",4.46
9,10.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.46
10,11.,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.34
11,12.,"""Dame Tu Cosita""[30]",El Chombo,"April 5, 2018",3.84
12,13.,"""Wheels on the Bus""[31]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.66
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.64
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.52
15,16.,"""Sorry""[34]",Justin Bieber,"October 22, 2015",3.51
16,17.,"""Counting Stars""[35]",OneRepublic,"May 31, 2013",3.51
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.40
18,19.,"""Girls Like You""[37]",Maroon 5,"May 31, 2018",3.23
19,20.,"""Faded""[38]",Alan Walker,"December 3, 2015",3.23
20,21.,"""Dark Horse""[39]",Katy Perry,"February 20, 2014",3.22
21,22.,"""Axel F""[40]",Crazy Frog,"June 16, 2009",3.22
22,23.,"""Let Her Go""[41]",Passenger,"July 25, 2012",3.17
23,24.,"""Bailando""[42]",Enrique Iglesias,"April 11, 2014",3.16
24,25.,"""Lean On""[43]",Major Lazer,"March 22, 2015",3.16
25,26.,"""Shake It Off""[44]",Taylor Swift,"August 18, 2014",3.14
26,27.,"""Baa Baa Black Sheep""[45]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.12
27,28.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.09
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.06
29,30.,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.04

**Q2)Scrape the details team India’s international fixtures from bcci.tv.<br>
Url = https://www.bcci.tv/.<br>
You need to find following details:<br>
A) Match title (I.e. 1
st ODI)<br>
B) Series<br>
C) Place<br>
D) Date<br>
E) Time<br>
Note: - From bcci.tv home page you have reach to the international fixture page through code.**

In [19]:
#cconnecting to the webdriver and opening the bcci.tv
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.bcci.tv/')

In [20]:
#going to the international page 
international=driver.find_element_by_xpath("//li[@class='nav-item ml-0']")
international

In [21]:
#clicking on the international page
international.click()

In [22]:
#scraping match title
match_title=[]
try:
    title=driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]')
    for i in title[1:]:
        match_title.append(i.text.replace("-"," "))
except NoSuchElementException:#handling no such element exception
    match_title.append("-") 

#scraping the place    
place=[]
try:
    loc=driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]')
    for i in loc[2:]:
        place.append(i.text)
except NoSuchElementException:#handling no such element exception
    place.append("-")

#scraping the series    
series=[]
try:
    serie=driver.find_elements_by_xpath('//div[@class="fixture-card-mid d-flex align-items-center justify-content-between"]')
    for i in serie[0:]:
        series.append(i.text.replace("\n"," "))
except NoSuchElementException:#handling no such element exception
    series.append("-")
    
#scraping the date     
date=[]
try:
    dates=driver.find_elements_by_xpath('//h5[@class="ng-binding"]')
    for i in dates[1:]:
        date.append(i.text)
except NoSuchElementException:#handling no such element exception
    date.append("-")
    
#scraping the time     
time=[]
try:
    times=driver.find_elements_by_xpath('//div[@class="match-card-right match-schedule "]')
    for i in times[1:]:
        time.append(i.text)
except NoSuchElementException:#handling no such element exception
    time.append("-")
time

In [42]:
#creating the DataFrame
df=pd.DataFrame({"Match_title":match_title,
                "Series":series,
                "Place":place,
                "Date":date,
                "Time":time})
df

,Match_title,Series,Place,Date,Time
0,4th ODI,New Zealand Women vs India Women,"John Davies Oval,",22 FEB 2022,3:30 AM IST
1,5th ODI,New Zealand Women vs India Women,"John Davies Oval,",24 FEB 2022,3:30 AM IST
2,1st T20I,India vs Sri Lanka,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,24 FEB 2022,7:00 PM IST
3,2nd T20I,India vs Sri Lanka,"Himachal Pradesh Cricket Association Stadium,",26 FEB 2022,7:00 PM IST
4,3rd T20I,India vs Sri Lanka,"Himachal Pradesh Cricket Association Stadium,",27 FEB 2022,7:00 PM IST
5,1st Test,India vs Sri Lanka,"Punjab Cricket Association IS Bindra Stadium,",4 MAR 2022,9:30 AM IST
6,1st ODI,Pakistan Women vs India Women,"Bay Oval,",6 MAR 2022,6:30 AM IST

**Q3)Scrape the details of selenium exception from guru99.com.<br>
Url = https://www.guru99.com/<br>
You need to find following details:<br>
A) Name<br>
B) Description<br>
Note: - From guru99 home page you have to reach to selenium exception handling page through code.**

In [79]:
#connecting to the webdriver and opening the guru99.com 
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.guru99.com/')

In [80]:
#going to the selenium exception handling page 
selenium=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
selenium.click()

In [81]:
#clicking on tutorial button 
tutorial=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a')
tutorial.click()

In [82]:
#scraping the name 
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in names[1:]:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception               
    name.append('No details available')

#scraping the description    
desc=[]
try:
    desc_list=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc_list[1:]:
        desc.append(i.text)
except NoSuchElementException:#handling no such element exception
    desc.append('No details available')  
    
    
#creating DataFrame
df=pd.DataFrame({"Names":name,
                 "Description":desc})
df

,Names,Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

**Q4)Scrape the details of State-wise GDP of India from statisticstime.com.<br>
Url = http://statisticstimes.com/<br>
You have to find following details:<br>
A) Rank<br>
B) State<br>
C) GSDP<br>
D) GSDP<br>
E) Share<br>
F) GDP($ billion)**<br>
**Note: - From statisticstimes home page you have to reach to economy page through code.**<br>

In [14]:
#connecting to the webdriver and opening the statisticstimes.com
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.statisticstimes.com/')

In [15]:
#clicking on economy button
economy=driver.find_element_by_xpath("//div[@class='dropdown'][2]/div/a[3]")
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))

#clicing on gdp of india    
indian=driver.find_element_by_xpath("//ul[@style='list-style-type:none;margin-left:20px;']//li[1]/a")
try:
    indian.click()
except ElementNotInteractableException:
    driver.get(indian.get_attribute('href'))

In [16]:
#scraping the rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException: #handling no such element exception                
    rank.append('-')

#scraping the state    
state=[]
try:
    states=driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]/table/tbody/tr/td[2]')
    for i in states:
        state.append(i.text)
except NoSuchElementException:#handling no such element exception
    state.append('-')
    
#scraping the GSDP(19-20)    
GSDP_20=[]
try:
    products=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in products:
        GSDP_20.append(i.text)
except NoSuchElementException:#handling no such element exception          
    GSDP_20.append('-')
    
#scraping the GSDP(18-19)     
GSDP_19=[]
try:
    product=driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]/table/tbody/tr/td[4]')
    for i in product:
        GSDP_19.append(i.text)
except NoSuchElementException:#handling no such element exception
    GSDP_19.append('-')
    
#scraping the share    
share=[]
try:
    shares=driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]/table/tbody/tr/td[5]')
    for i in shares:
        share.append(i.text)
except NoSuchElementException:#handling no such element exception
    share.append("-")

#scraping the GDP(billion$)    
GDP=[]
try:
    gross=driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]/table/tbody/tr/td[6]')
    for i in gross:
        GDP.append(i.text)
except NoSuchElementException:#handling no such element exception
    GDP.append("-")

In [17]:
#creating the DataFrame
df=pd.DataFrame({"Rank":rank,
                "State":state,
                "GSDP 19-20":GSDP_20,
                "GSDP 18-19":GSDP_19,
                "Share":share,
                "GDP":GDP})
df

   Rank                      State GSDP 19-20 GSDP 18-19   Share      GDP
0     1                Maharashtra          -  2,632,792  13.94%  399.921
1     2                 Tamil Nadu  1,845,853  1,630,208   8.63%  247.629
2     3              Uttar Pradesh  1,687,818  1,584,764   8.39%  240.726
3     4                    Gujarat          -  1,502,899   7.96%  228.290
4     5                  Karnataka  1,631,977  1,493,127   7.91%  226.806
5     6                West Bengal  1,253,832  1,089,898   5.77%  165.556
6     7                  Rajasthan  1,020,989    942,586   4.99%  143.179
7     8             Andhra Pradesh    972,782    862,957   4.57%  131.083
8     9                  Telangana    969,604    861,031   4.56%  130.791
9    10             Madhya Pradesh    906,672    809,592   4.29%  122.977
10   11                     Kerala          -    781,653   4.14%  118.733
11   12                      Delhi    856,112    774,870   4.10%  117.703
12   13                    Haryana    831,610    734,163   3.89%  111.519
13   14                      Bihar    611,804    530,363   2.81%   80.562
14   15                     Punjab    574,760    526,376   2.79%   79.957
15   16                     Odisha    521,275    487,805   2.58%   74.098
16   17                      Assam          -    315,881   1.67%   47.982
17   18               Chhattisgarh    329,180    304,063   1.61%   46.187
18   19                  Jharkhand    328,598    297,204   1.57%   45.145
19   20                Uttarakhand          -    245,895   1.30%   37.351
20   21            Jammu & Kashmir          -    155,956   0.83%   23.690
21   22           Himachal Pradesh    165,472    153,845   0.81%   23.369
22   23                        Goa     80,449     73,170   0.39%   11.115
23   24                    Tripura     55,984     49,845   0.26%    7.571
24   25                 Chandigarh          -     42,114   0.22%    6.397
25   26                 Puducherry     38,253     34,433   0.18%    5.230
26   27                  Meghalaya     36,572     33,481   0.18%    5.086
27   28                     Sikkim     32,496     28,723   0.15%    4.363
28   29                    Manipur     31,790     27,870   0.15%    4.233
29   30                   Nagaland          -     27,283   0.14%    4.144
30   31          Arunachal Pradesh          -     24,603   0.13%    3.737
31   32                    Mizoram     26,503     22,287   0.12%    3.385
32   33  Andaman & Nicobar Islands          -          -       -        -

**Q5)Scrape the details of trending repositories on Github.com.<br>
Url = https://github.com/<br>
You have to find the following details:<br>
A) Repository title<br>
B) Repository description<br>
C) Contributors count<br>
D) Language used**<br>
**Note: - From the home page you have to click on the trending option from Explore menu through code.**

In [2]:
#connecting to the webdriver and opening the github.com
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://github.com/')

In [3]:
#going to the trending page 
driver.get(driver.find_element_by_xpath('//ul[@class="d-lg-flex list-style-none"]//li[4]//ul[@class="list-style-none f5 pb-1"]//li[5]//a').get_attribute('href'))

In [4]:
#scraping the repository title
repo_title=[]
try:
    title=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
    for i in title:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append("-") 

#scraping the language used     
language_used=[]
try:
    lang=driver.find_elements_by_xpath('//div[@class="f6 color-fg-muted mt-2"]/span[1]')
    for i in lang:
        language_used.append(i.text)
except NoSuchElementException:#handling no such element exception
    language_used.append("-") 
    
#scraping the repository description  
repo_desc=[]
try:
    desc=driver.find_elements_by_xpath('//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in desc:
        repo_desc.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_desc.append("-")
    
#scraping the contributors count     
Contributors_count=[]
Contributors_url=[]

i=1

while True:
    try:
        Contributors_url.append(driver.find_element_by_xpath(f'//div//article[@class="Box-row"][{i}]//h1[@class="h3 lh-condensed"]//a').get_attribute('href'))
        i+=1
    except:
       
       break
        
for i in Contributors_url:
    driver.get(i)
    time.sleep(2)
    try:
        Contributors_count.append(driver.find_element_by_xpath('//div[@class="BorderGrid BorderGrid--spacious"]').text.split('Contributors')[1].split('\n')[0])     
    except:
        Contributors_count.append('-')

In [5]:
#creating the DataFrame
df=pd.DataFrame({"Repository_Title":repo_title,
                "Repository_Description":repo_desc,
                "Language_Used":language_used,
                "Contributors_count":Contributors_count}) 
df

,Repository_Title,Repository_Description,Language_Used,Contributors_count
0,Anduin2017 / HowToCook,程序员在家做饭方法指南。,Built by,50
1,lwthiker / curl-impersonate,curl-impersonate: A special compilation of cur...,Dockerfile,2
2,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,Python,112
3,cryptotwinsbr / spacecrypto-bot,This is a free python bot program that crosses...,Python,2
4,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,JavaScript,"4,395"
5,saadeghi / daisyui,⭐️ ⭐️ ⭐️ ⭐️ ⭐️ Tailwind Components,Svelte,27
6,emilk / egui,egui: an easy-to-use immediate mode GUI in Rus...,Rust,117
7,iranremote / awesome-iran-remote,A list of remote-friendly or full-remote compa...,Built by,-
8,libevent / libevent,Event notification library,C,196
9,littlefs-project / littlefs,A little fail-safe filesystem designed for mic...,C,32
10,swisskyrepo / PayloadsAllTheThings,A list of useful payloads and bypass for Web A...,Python,180
11,BishopFox / unredacter,Never ever ever use pixelation as a redaction ...,TypeScript,2
12,supabase / supabase,The open source Firebase alternative. Follow t...,TypeScript,315
13,harmonoid / harmonoid,🎵 Elegant music app to play & manage music lib...,Dart,17
14,openai / gym,A toolkit for developing and comparing reinfor...,Python,333
15,withfig / autocomplete,Fig adds autocomplete to your terminal.,TypeScript,180
16,openvinotoolkit / anomalib,An anomaly detection library comprising state-...,Python,7
17,odin-lang / Odin,Odin Programming Language,Odin,93
18,google / googletest,GoogleTest - Google Testing and Mocking Framework,C++,352
19,beurtschipper / Depix,Recovers passwords from pixelized screenshots,Python,8
20,metowolf / vCards,📡️ vCards 中国黄页 - 优化 iOS/Android 来电、信息界面体验,JavaScript,15
21,neovim / neovim,Vim-fork focused on extensibility and usability,Vim script,753
22,NVlabs / instant-ngp,Instant neural graphics primitives: lightning ...,Cuda,8
23,spring-projects / spring-petclinic,A sample Spring-based application,CSS,73
24,trustwallet / assets,"A comprehensive, up-to-date collection of info...",Go,"3,442"

**Q6)Scrape the details of top 100 songs on billiboard.com.<br>
Url = https:/www.billboard.com/<br>
You have to find the following details:<br>
A) Song name<br>
B) Artist name<br>
C) Last week rank<br>
D) Peak rank<br>
E) Weeks on board<br>
Note: - From the home page you have to click on the charts option then hot 100-page link through code.**

In [46]:
#connecting to the webdriver and opening the billboard.com
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.billboard.com/')

In [47]:
#clicking on chart button
chart=driver.find_element_by_xpath("/html/body/div[4]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]/a").click()

In [48]:
#clicking on hotpage button
hotpage=driver.find_element_by_xpath("/html/body/div[4]/header/div[2]/div/nav/ul/li[1]/a").click()

In [49]:
#scraping the song name 
song_name=[]
try:
    names=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li/h3")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    song_name.append('-')   
    
#scraping the artist nbame     
artist_name=[]
try:
    name=driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[1]/span")
    for i in name:
        artist_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist_name.append('-')
    
#scraping the peak rank     
peak_rank=[]
try:
    rank=driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[5]")
    for i in rank:
        peak_rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    peak_rank.append('-') 
    
#scraping last week rank     
lw_rank=[]
try:
    rank=driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[4]")
    for i in rank:
        lw_rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    lw_rank.append('-')  
    
#scraping weeks on board     
weeks_on_board=[]
try:
    weeks=driver.find_elements_by_xpath("//li[@class='lrv-u-width-100p']/ul/li[6]")
    for i in weeks:
        weeks_on_board.append(i.text)
except NoSuchElementException:#handling no such element exception
     weeks_on_board.append('-') 
        
#creatuing the DataFrame        
df=pd.DataFrame({"Song_name":song_name,
                "Artist_name":artist_name,
                "Last_weak_rank":lw_rank,
                "Peak_rank":peak_rank,
                "Weeks_on_board":weeks_on_board})
df

,Song_name,Artist_name,Last_weak_rank,Peak_rank,Weeks_on_board
0,We Don't Talk About Bruno,"Carolina Gaitan, Mauro Castillo, Adassa, Rhenz...",1,1,7
1,Do We Have A Problem?,Nicki Minaj X Lil Baby,-,2,1
2,Easy On Me,Adele,2,1,18
3,Heat Waves,Glass Animals,3,3,56
4,Stay,The Kid LAROI & Justin Bieber,4,1,31
...,...,...,...,...,...
95,Iffy,Chris Brown,87,71,4
96,When I'm Gone,Alesso / Katy Perry,-,97,1
97,Fair Trade,Drake Featuring Travis Scott,90,3,17
98,Megan's Piano,Megan Thee Stallion,97,97,2
99,Moth To A Flame,Swedish House Mafia & The Weeknd,-,27,8

**Q7)Scrape the details of Data science recruiters from naukri.com.<br>
Url = https://www.naukri.com/<br>
You have to find the following details:<br>
A) Name<br>
B) Designation<br>
C) Company<br>
D) Skills they hire for<br>
E) Location<br>
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code**

In [31]:
#connecting to the webdriver and opening the naukri.com
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.naukri.com/data-collection-recruiters')

In [34]:
#scraping the name 
name=[]
try:
    names=driver.find_elements_by_xpath('//a[@class="ellipsis"]/span')
    for i in names:
        name.append(i.text)
except NOSuchElementException:#handling no such element exception
    name.append('-')
    
#scraping the designation    
designation=[]
try:
    desg=driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')
    for i in desg:
        designation.append(i.text)
except NOSuchElementException:#handling no such element exception
    designation.append('-')  
    
#scraping the company    
company=[]
try:
    comp=driver.find_elements_by_xpath('//a[@class="ellipsis"][2]')
    for i in comp:
        company.append(i.text)
except NOSuchElementException:#handling no such element exception
    company.append('-') 
    
#scraping the skills
skills=[]
try:
    skill=driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')
    for i in skill:
        skills.append(i.text)
except NOSuchElementException:#handling no such element exception
    skill.append('-')
    
#scraping the location    
location=[]
try:
    locn=driver.find_elements_by_xpath('//small[@class="ellipsis"]')
    for i in locn:
        location.append(i.text)
except NOSuchElementException:#handling no such element exception
    location.append('-')

In [48]:
#creating the DataFrame
df=pd.DataFrame({"Name":name,
                "Designation":designation,
                "Company":company,
                "Location":location,
                "Skills":skills})
df

,Name,Designation,Company,Location,Skills
0,Susi,Company HR,Find Live Infotech,Chennai,"Data Entry, Part Time, Computer Operating, Sal..."
1,mayank modi,Company Recruiter,UNITED CAPITAL CLUB tourism service pvt....,Ahmedabad,"Tourism, Travel, Hr, Joining Formalities, Recr..."
2,MONA,Company HR,Find live Technology,Chennai,"Data Entry Operation, Part Time, Typing, data ..."
3,Dipali Dalela,Company Recruiter,"EMBELLISHMENT (Lakme Academy,Indira Nagar)",Lucknow,"marketing, sales, telecalling, telemarketing, ..."
4,HR Datakatalyst,Company HR,Datakatalyst Solutions Pvt. Ltd,Pune,"Recruitment, Interviewing, Staffing, Hr, Sourc..."
5,UDIT GUPTA,Company Recruiter,J-PAL,Ahmedabad,"Field Survey, Data Collection, Environmental E..."
6,VENKATESH,Company HR,POCLAINHYDRAULICS,Pondicherry,"Ms Office, Oracle, Purchase, Sourcing, RFQ, Da..."
7,Ruchika,Company HR,Ouline OVerseas Co,Delhi,"Sales Executive Activities, Stationery, Pen, D..."
8,P K Gendre,Company HR,apanka.com,Bilaspur,"Marketing, Advertising, Data Collection"
9,Om Joshi,Company HR,Speed Telecom,Noida,"Brand Promotion, Market Data, Data Collection,..."
10,DEEP GOEL,Company HR,Stymin Corporation (We solve PMJDY Quires...,Gurgaon,"Research, Training, It, Project Management, In..."
11,tal,Company HR,Tal consultancies,Ludhiana,"Part Time, Internet Surfing, Social Media Mark..."
12,Bikash Pandey,Company HR,KCC CLASSES,Dehradun,"marketing, branding, Admission Counselling, Da..."
13,Juliana Prabhu,Company HR,Chilasa Business Growth Services,Chennai,"Social Media, Web Technologies, Media Strategy..."
14,kasthuri,Company HR,FIND LIVE INFO,Chennai,"Part Time, Data Collection, Data Processing, C..."
15,Alok,Company HR,i-Bits,Maharashtra - Other,"Marketing, Business Development, Sales, Busine..."
16,Sreekanth Putsala,Company HR,Aquilus International Pvt Ltd,Hyderabad / Secunderabad,"Business Development, Life Sciences, Microbiol..."
17,akshay,company HR,united capital club,Mumbai,"Part Time, Freelancing, Online Marketing, Onli..."
18,Alok Goenka,Company HR,Net's and Web's,Amravati,"Marketing Campaigns, Branding, New Business De..."
19,Naresh azad singh,Company HR,Bhojanguru.com,Ghaziabad,"Data Collection, Data Entry, Marketing"
20,Rakhi Mb,Head of Operations HR,CogentPoint,Ahmedabad,"Sales, Marketing, Business Development, Brandi..."
21,Amit Verma,HR,Digital Global Services,Ludhiana,"Bulk Hiring, Field Executive, Data Collection,..."
22,dream true,HR,dreamtrue,Mohali,"Business Development, Bidding, Sales Managemen..."
23,Anand Kushwaha,HR Recruiter,Recmon,Uttar Pradesh - Other,"Business Development Management, Educational S..."
24,Priyanka Gour,HR Executive,Aladinn Technology Pvt. Ltd.,Pune,"Web Designing, Web Development, Content Writin..."
25,HR Anil,HR Recruiter,Recruitment,Tirupati,"Java, .Net, Networking, Hardware Networking, S..."
26,Dehaat Store,HR Manager,Dehaat Store,Delhi,"Marketing, Retail Sales, Branding, Btl, Franch..."
27,SNEHA,HR,SNEHA,Mumbai,"Talent Acquisition, Documentation, Coordinatio..."
28,Satheesh Kumar,HR Manager,"Maharaja Silks &amp; Readymades,...",Tamil Nadu - Other,"Marketing, Crm, Advertising, Administration, S..."
29,Shweta Saraf,Sr Executive HR,Parity Cube Pvt Ltd,Mumbai,"Software Development, Seo Specialist, Ui / Ux ..."
30,Make Mi Holidays,Hr Head,makemiholidays,Bengaluru / Bangalore,"Marketing, Human Resource Management, Travel A..."
31,Sanyogita,HR Executive,S. I. Energy Ventures Pvt. Ltd.,Delhi,"mysql, Visual Studio, vba, Vb.net, Visual Basi..."
32,Ani,HR Recruiter,HR MARS,Chandigarh,"Marketing, Data Collection"
33,kanika sharma,Sr Hr Manager,appin technologies,Bhopal,"Communication Skills, Convincing Power, good k..."
34,Soffie,Assistant Human Resources,ZTEsoft Technology India Private Ltd,Delhi,A) Responsible For Billing/charging System Imp...
35,Subramanyam Adapa,Director,Sri Sai Manasa Nature Tech Pvt Ltd,Hyderabad / Secunderabad,"Environmental Impact Assessment, Waste Water T..."
36,Singh Enterprises,Owner,Singh Enterprises,Noida,"Telecalling, Customer Service, Data Entry, Cli..."
37,Bhomyo,Channel Partner,Bhomyo,Bhavnagar,"Sales Executive Activities, Marketing, Data Co..."
38,Akilesh,Chief Executive Officer,Alteron,Chennai,"Digital Marketing, Social Media, Youtube, Part..."
39,Rashid,Director,ASR Infocom,Meerut,"Technical Support, Information Technology, Tel..."
40,vaamexhibition,Founder CEO,expo hub,Ahmedabad,"Exhibitions, Graphic Designing, Design, 3D, In..."
41,Saptarshi Guria,Director Operations,Florence diagnostic,West Bengal - Other,"Diagnostics, Healthcare, Help Desk Operations,..."
42,BOBBY,Company HR,MASS MEDIA,Chennai,"Back Office, Data Entry, Advertising, Marketin..."
43,Sanaya Ranade,Hiring Manager,Megavenues.com,Pune,"Sales, Business Development, Software Developm..."
44,Ravi,Market Research Analyst,BMRB,Hyderabad / Secunderabad,"Data Collection, Marketing Communication"
45,Devi,Company HR,Nissi Infotech,Coimbatore,"Data Collection, Email Marketing, Database Mar..."
46,Binod Suri,Company HR,Gill Travel,Delhi,"SEO, Forum Posting, Social Bookmarking, Blog P..."
47,Manish Kumar Jha,CEO/Director,Studentcosy Property Solution Private...,GAYA,"Data Collection, Data Collection Executive, Da..."
48,Nazish Laeiq,Head of HR and Admin,ITM Group of Institutions,Aligarh,"Bpo, Teaching, Customer Engineer, Assistant Pr..."
49,Sunil Kumar,Company HR,eSeller Sahayak,Varanasi / Banaras,"Ecommerce Development, Sales, Marketing, Data ..."

**Q8). Scrape the details of Highest selling novels.<br>
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/<br>
You have to find the following details:<br>
A) Book name<br>
B) Author name<br>
C) Volumes sold<br>
D) Publisher<br>
E) Genre**

In [86]:
#connecting to the webdriver and opening the theguardian.com
driver=webdriver.Chrome("chromedriver.exe")
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [6]:
#scraping the book name
book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:#handling no such element exception   
    book_name.append('-')

#scraping the author name     
author_name=[]
try:
    name=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('-')
    
#scraping the sale    
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('-')
    
#scraping the publisher    
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('-')
    
#scraping the genre     
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('-')

In [8]:
#creating the DatFrame 
df=pd.DataFrame({})
df['Book_name']=book_name
df['Author_name']=author_name
df['Volumes_sold']=Sale
df["Publisher"]=publisher
df['Genre']=genre
df

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Da Vinci Code,The","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,Harry Potter and the Deathly Hallows,"4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,Harry Potter and the Philosopher's Stone,"4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix,"4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,Fifty Shades of Grey,"3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Ghost,The","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,Happy Days with the Naked Chef,"794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Hunger Games,The:Hunger Games Trilogy","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Lost Boy,The:A Foster Child's Search for the L...","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,Jamie's Ministry of Food:Anyone Can Learn to C...,"791,095",Penguin,Food & Drink: General

**Q9)9. Scrape the details most watched tv series of all time from imdb.com.<br>
Url = https://www.imdb.com/list/ls095964455/<br>
You have to find the following details:<br>
A) Name<br>
B) Year span<br>
C) Genre<br>
D) Run time<br>
E) Ratings<br>
F) Votes**

In [9]:
#connecting to the webdriver and opening the imdb.com
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://www.imdb.com/list/ls095964455/')

In [10]:
#scraping the names
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('-')

#scraping the years
years=[]
try:
    year=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in year:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('-')

#scraping the genre    
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('-')
    
#scraping the run time
run_time=[]
try:
    time=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in time:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('-')

#scraping the rating
rating=[]
try:
    ratings=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in ratings:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('-')

#scraping the votes
votes=[]
try:
    vote=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in vote:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('-')
    
#creating the DataFrame
df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,952,243"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"963,077"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"929,677"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"278,481"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"238,684"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"47,660"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"58,392"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"185,046"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"39,119"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"221,189"

**Q10)Details of Datasets from UCI machine learning repositories.<br>
Url = https://archive.ics.uci.edu/<br>
You have to find the following details:<br>
A) Dataset name<br>
B) Data type<br>
C) Task<br>
D) Attribute type<br>
E) No of instances<br>
F) No of attribute<br>
G) Year<br>
Note: - from the home page you have to go to the ShowAllDataset page through code.**

In [102]:
#connectoing to the webdriver and opening the archive.ics.uci.edu
driver=webdriver.Chrome('chromedriver.exe')
driver.get('https://archive.ics.uci.edu/ml/index.php')

In [103]:
#clicking on repository button 
respository=driver.find_element_by_xpath("//span[@class='normal']/b/a")
respository.click()

In [104]:
#scraping the datesheet name 
dataset_name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        dataset_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    datatset_name.append('-')

#scraping the datesheet type    
dataset_type=[]
try:
    types=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')
    for i in types[1:]:
        dataset_type.append(i.text)
except NoSuchElementException:#handling no such element exception
    dataset_type.append('-')

#scraping the task    
Task=[]    
try:
    task=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:#handling no such element exception
    Task.append('-')    

#scraping the attribute    
Attribute=[]    
try:
    attribute=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        Attribute.append(i.text)
except NoSuchElementException:#handling no such element exception
    Attribute.append('-')
    
#scraping number of instance     
No_of_Instance=[]
try:
    instance=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        No_of_Instance.append(i.text)
except NoSuchElementException:#handling no such element exception
    No_of_Instance.append('-')
    
#scraping number of attribute      
No_of_Attribute=[]
try:
    attribute_no=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attribute_no[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:#handling no such element exception
    No_of_Attribute.append('-')

#scraping the year     
Year=[]
try:
    year=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:#handling no such element exception
    Year.append('-')

In [105]:
#creating the DataFrame
df=pd.DataFrame({"Dataset Name":dataset_name,
                 "Data Type":dataset_type,
                 "Default Task":Task,
                 "Attribute Type":Attribute, 
                 "No of instances":No_of_Instance,
                 "No of atrributes":No_of_Attribute, "Year":Year})
df

,Dataset Name,Data Type,Default Task,Attribute Type,No of instances,No of atrributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021